import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
	const products = trpc.useQuery(["products.get"]);

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<header className="w-screen flex justify-center items-center h-16 font-bold text-3xl">
					All Products
				</header>

				<section>
					{products.data?.map((p) => (
						<div key={p.id}></div>
					))}
				</section>
			</main>
		</>
	);
};

export default Home;
